name: md
channels:
  - pyg
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.4.4=py39h06a4308_0
  - aiohttp=3.11.10=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=5.0.1=py39h06a4308_0
  - attrs=24.3.0=py39h06a4308_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.4.26=py39h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvcc=12.1.105=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=3
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.17.0=py39h06a4308_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.5.0=py39h5eee18b_0
  - fsspec=2025.3.2=py39he3bba80_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py39h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=hde9077f_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py39h06a4308_0
  - multidict=6.1.0=py39h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py39h06a4308_0
  - numpy=2.0.1=py39h5f9d8c6_1
  - numpy-base=2.0.1=py39hb5e798b_1
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.16=h5eee18b_0
  - pillow=11.1.0=py39hac6e08b_1
  - pip=25.1=pyhc872135_2
  - propcache=0.3.1=py39h5eee18b_0
  - psutil=5.9.0=py39h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=4=hd3eb1b0_1
  - pyg=2.6.1=py39_torch_2.4.0_cu121
  - pyparsing=3.2.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.23=he99959a_0
  - pytorch=2.4.1=py3.9_cuda12.1_cudnn9.1.0_0
  - pytorch-cluster=1.6.3=py39_torch_2.4.0_cu121
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py39_torch_2.4.0_cu121
  - pytorch-sparse=0.6.18=py39_torch_2.4.0_cu121
  - pyyaml=6.0.2=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py39h06a4308_1
  - scipy=1.13.1=py39h5f9d8c6_1
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py39h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - torchaudio=2.4.1=py39_cu121
  - torchtriton=3.0.0=py39
  - torchvision=0.19.1=py39_cu121
  - tqdm=4.67.1=py39h2f386ee_0
  - typing-extensions=4.12.2=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - urllib3=2.3.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py39h5eee18b_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.3.0
      - accelerate==1.7.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - beautifulsoup4==4.13.4
      - captum==0.2.0
      - cilog==1.3.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - dive-into-graphs==1.1.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fonttools==4.58.4
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.73.0
      - h5py==3.14.0
      - hf-xet==1.1.3
      - huggingface-hub==0.33.0
      - hydra-core==1.3.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - jedi==0.19.2
      - joblib==1.5.1
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - markdown==3.8
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - munch==4.0.0
      - mypy-extensions==1.1.0
      - numba==0.60.0
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.0
      - parso==0.8.4
      - peft==0.15.2
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.6
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyscf==2.9.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - rdkit-pypi==2022.9.5
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - shap==0.48.0
      - six==1.17.0
      - slicer==0.0.8
      - smmap==5.0.2
      - soupsieve==2.7
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - traitlets==5.14.3
      - transformers==4.52.4
      - typed-argument-parser==1.7.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - wandb==0.20.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - zipp==3.23.0
prefix: /home/gmc/anaconda3/envs/md
